ftl v. gravity db migration new script

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -101,6 +101,10 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 
 sed -i "s|\${piholeGitDir}/advanced/Templates/gravity|/opt/pihole/gravity|w $_ssc" "$dirb"/gravity.sh
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 3" && exit 1 ; fi
 
+# setup gravity.db.sh
+sed -i "s|/etc/.pihole/advanced/Scripts/database_migration/gravity|/opt/pihole/database_migration/gravity|w $_ssc" "$dirb"/advanced/Scripts/database_migration/gravity-db.sh
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi
+
 # setup pihole
 sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dirb"/pihole
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 1" && exit 1 ; fi
