corrected old part, need more love

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -15,151 +15,151 @@ tar xf v$pkgver.tar.gz
 cp -a $dira $dirb
 
 # the return of service management
-sed -i "s|service \${resolver} \${svcOption}|systemctl \${svcOption} pi-hole-ftl|w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && return 1 ; fi
+sed -i "s|service \${resolver} \${svcOption}|systemctl \${svcOption} \${resolver}|w $_ssc" "$dirb"/pihole
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && exit 1 ; fi
 
 # setting up and securing pihole wrapper script
 #sed -n "/debugFunc() {/w $_ssc" "$dirb"/pihole
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 1" && return 1 ; fi
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 1" && exit 1 ; fi
 #sed -i '/debugFunc() {/,+16d' "$dirb"/pihole
 
 sed -n "/flushFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
 sed -i '/flushFunc() {/,+4d' "$dirb"/pihole
 
 sed -n "/versionFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
 sed -i '/versionFunc() {/,+4d' "$dirb"/pihole
 
 sed -n "/updatePiholeFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
 sed -i '/updatePiholeFunc() {/,+5d' "$dirb"/pihole
 
 sed -n "/reconfigurePiholeFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
 sed -i '/reconfigurePiholeFunc() {/,+4d' "$dirb"/pihole
 
 sed -n "/chronometerFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
 sed -i '/chronometerFunc() {/,+4d' "$dirb"/pihole
 
 sed -n "/uninstallFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 4" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 4" && exit 1 ; fi
 sed -i '/uninstallFunc() {/,+4d' "$dirb"/pihole
 
 sed -n "/piholeCheckoutFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 5" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 5" && exit 1 ; fi
 sed -i '/piholeCheckoutFunc() {/,+22d' "$dirb"/pihole
 
 sed -n "/tricorderFunc() {/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
 sed -i '/tricorderFunc() {/,+30d' "$dirb"/pihole
 
 sed -n "/\"\-[r,up]/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 7" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 7" && exit 1 ; fi
 sed -i '/\"\-[r,up]/d' "$dirb"/pihole
 
 sed -n "/^  \-[r,t,l,f],/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
 sed -i '/^  \-[r,t,l,f],/d' "$dirb"/pihole
 
 sed -n "/^  \-up,/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
 sed -i '/^  \-up,/d' "$dirb"/pihole
 
 sed -n "/^  \-a,/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
 sed -i '/^  \-a,/,+1d' "$dirb"/pihole
 
 sed -n "/uninstall/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
 sed -i '/uninstall/d' "$dirb"/pihole
 
 sed -i "s|^  checkout.*$|\";|w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && exit 1 ; fi
 
 sed -n "/checkout/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
 sed -i '/checkout/d' "$dirb"/pihole
 
 sed -n "/tricorder/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
 sed -i '/tricorder/d' "$dirb"/pihole
 
 sed -n "/updatechecker/w $_ssc" "$dirb"/pihole
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 19" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 19" && exit 1 ; fi
 sed -i '/updatechecker/d' "$dirb"/pihole
 
 # -----------------
 
 # setup gravity.sh
 sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dirb"/gravity.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi
 
 # -----------------
 
 # setting up and securing webpage.sh script
 sed -n "/SetWebPassword() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 1" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 1" && exit 1 ; fi
 sed -i '/SetWebPassword() {/,+44d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/SetTemperatureUnit() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 2" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 2" && exit 1 ; fi
 sed -i '/SetTemperatureUnit() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/SetExcludeDomains() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 3" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 3" && exit 1 ; fi
 sed -i '/SetExcludeDomains() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/SetExcludeClients() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 4" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 4" && exit 1 ; fi
 sed -i '/SetExcludeClients() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/EnableDHCP() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 5" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 5" && exit 1 ; fi
 sed -i '/EnableDHCP() {/,+17d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/DisableDHCP() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 6" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 6" && exit 1 ; fi
 sed -i '/DisableDHCP() {/,+11d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/SetWebUILayout() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 7" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 7" && exit 1 ; fi
 sed -i '/SetWebUILayout() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/SetPrivacyMode() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 8" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 8" && exit 1 ; fi
 sed -i '/SetPrivacyMode() {/,+7d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/\"\-[p,c,f,k]/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
 sed -i '/\"\-[p,c,f,k]/d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/  \-[p,c,f,k]/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
 sed -i '/  \-[p,c,f,k]/d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -n "/\"setexcludedomains/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && exit 1 ; fi
 sed -i '/\"setexcludedomains/d' "$dirb"/advanced/Scripts/webpage.sh
 sed -n "/\"setexcludeclients/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 11" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 11" && exit 1 ; fi
 sed -i '/\"setexcludeclients/d' "$dirb"/advanced/Scripts/webpage.sh
 sed -n "/\"enabledhcp/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 12" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 12" && exit 1 ; fi
 sed -i '/\"enabledhcp/d' "$dirb"/advanced/Scripts/webpage.sh
 sed -n "/\"disabledhcp/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 13" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 13" && exit 1 ; fi
 sed -i '/\"disabledhcp/d' "$dirb"/advanced/Scripts/webpage.sh
 sed -n "/\"layout/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 14" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 14" && exit 1 ; fi
 sed -i '/\"layout/d' "$dirb"/advanced/Scripts/webpage.sh
 sed -n "/\"privacymode/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && exit 1 ; fi
 sed -i '/\"privacymode/d' "$dirb"/advanced/Scripts/webpage.sh
 
 sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && return 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && exit 1 ; fi
 
 # -----------------
 # adlists.default is gone and adlists.list is populated by install script
