no teleport on webpage.sh, privacy level cleanup

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 _pkgver=5.17.1
-_pkgrel=1
+_pkgrel=2
 source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
 dircorea="pi-hole-$_pkgver"
 dircoreb="$dircorea.cust"
@@ -161,6 +161,12 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bi
 
 # -----------------
 
+# webroot setup
+sed -i "s|webroot=\"/var/www/html\"|webroot=\"/srv/http/pihole\"|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: webroot setup" && exit 1 ; fi
+
+# -----------------
+
 # teleport.php hardcoded path
 #sed -i "s|/var/www/html/admin/|/srv/http/pihole/admin/|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
 #if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: teleport.php hardcoded path 1" && exit 1 ; fi
@@ -206,35 +212,39 @@ sed -n "/SetPrivacyLevel() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 8" && exit 1 ; fi
 sed -i '/SetPrivacyLevel() {/,+7d' "$dircoreb"/advanced/Scripts/webpage.sh
 
-sed -n "/\"\-[p,c,f,k]/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+sed -n "/Teleporter() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
-sed -i '/\"\-[p,c,f,k]/d' "$dircoreb"/advanced/Scripts/webpage.sh
+sed -i '/Teleporter() {/,+13d' "$dircoreb"/advanced/Scripts/webpage.sh
 
-sed -n "/  \-[p,c,f,k]/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
-sed -i '/  \-[p,c,f,k]/d' "$dircoreb"/advanced/Scripts/webpage.sh
+sed -n "/\"\-[p,c,f,k,l,t]/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && exit 1 ; fi
+sed -i '/\"\-[p,c,f,k,l,t]/d' "$dircoreb"/advanced/Scripts/webpage.sh
+
+sed -n "/  \-[p,c,f,k,l,t]/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && exit 1 ; fi
+sed -i '/  \-[p,c,f,k,l,t]/d' "$dircoreb"/advanced/Scripts/webpage.sh
 
 sed -n "/\"setexcludedomains/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 11" && exit 1 ; fi
 sed -i '/\"setexcludedomains/d' "$dircoreb"/advanced/Scripts/webpage.sh
 sed -n "/\"setexcludeclients/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 11" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 12" && exit 1 ; fi
 sed -i '/\"setexcludeclients/d' "$dircoreb"/advanced/Scripts/webpage.sh
 sed -n "/\"enabledhcp/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 12" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 13" && exit 1 ; fi
 sed -i '/\"enabledhcp/d' "$dircoreb"/advanced/Scripts/webpage.sh
 sed -n "/\"disabledhcp/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 13" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 14" && exit 1 ; fi
 sed -i '/\"disabledhcp/d' "$dircoreb"/advanced/Scripts/webpage.sh
 sed -n "/\"layout/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 14" && exit 1 ; fi
-sed -i '/\"layout/d' "$dircoreb"/advanced/Scripts/webpage.sh
-sed -n "/\"privacylevel/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && exit 1 ; fi
-sed -i '/\"privacylevel/d' "$dircoreb"/advanced/Scripts/webpage.sh
+sed -i '/\"layout/d' "$dircoreb"/advanced/Scripts/webpage.sh
+#sed -n "/\"privacylevel/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 16" && exit 1 ; fi
+#sed -i '/\"privacylevel/d' "$dircoreb"/advanced/Scripts/webpage.sh
 
 #sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
-#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 16" && exit 1 ; fi
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 17" && exit 1 ; fi
 
 # -----------------
 
