teleport wrong hardcoded path

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -144,6 +144,12 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bi
 
 # -----------------
 
+# teleport.php hardcoded path
+sed -i "s|/var/www/html/admin/|/srv/http/pihole/|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: teleport.php hardcoded path 1" && exit 1 ; fi
+
+# -----------------
+
 # change FTL port file location to chronometer.sh
 sed -i "s|\${PI_HOLE_FILES_DIR}/automated install/basic-install.sh|/opt/pihole/basic-install.sh|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change FTL port file location to chronometer.sh" && exit 1 ; fi
